language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t ragabi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ragabi/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-poc"
  env: "DockerPoc-env"
  bucket_name: "elasticbeanstalk-eu-central-1-905361737081"
  bucket_path: "docker-poc"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
